version: '3'
services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3308
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
  myapp-main:
    image: dariuszkusak/phone-app
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3308

